title: "Weekly listening prompt"
labels: ["weekly-prompt"]
body:
  - type: markdown
    attributes:
      value: |
        A weekly prompt to keep the participation loop alive.

  - type: input
    id: week
    attributes:
      label: Week
      placeholder: "2026-W05"
    validations:
      required: true

  - type: input
    id: track
    attributes:
      label: Track
      placeholder: "Decompression Etude 2"
    validations:
      required: true

  - type: textarea
    id: prompt
    attributes:
      label: Prompt
      placeholder: |
        Constraints (pick 1–3):
        - only 3 primitives
        - no FFT (envelope + centroid only)
        - maintain a state across 20 loops

        Deliverables:
        - 1 still or 10–30s loop
        - 5–15 lines of listening log
    validations:
      required: true

  - type: input
    id: deadline
    attributes:
      label: Deadline (optional)
      placeholder: "Sunday 23:59 UTC"
    validations:
      required: false
